//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_JobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyJob
    {
        public int ApplyId { get; set; }
        public int JobId { get; set; }
        public int Co_Id { get; set; }
        public int Us_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Resume { get; set; }
        public string ApplyStatus { get; set; }
    }
}
