//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_JobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyReg_Tab
    {
        public int Co_Id { get; set; }
        public string Co_Name { get; set; }
        public string Co_Address { get; set; }
        public string Co_Email { get; set; }
        public long Co_Phone { get; set; }
        public string Co_Status { get; set; }
    }
}
