//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project_JobSearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReg_Tab
    {
        public int Us_Id { get; set; }
        public string Us_Name { get; set; }
        public string Us_Address { get; set; }
        public int Us_Age { get; set; }
        public string Us_Gender { get; set; }
        public long Us_Phone { get; set; }
        public string Us_Email { get; set; }
        public string Us_State { get; set; }
        public string Us_District { get; set; }
        public int Us_Pincode { get; set; }
        public string Us_Qualification { get; set; }
        public decimal Us_CGPA { get; set; }
        public string Us_Skills { get; set; }
        public string Us_Status { get; set; }
    }
}
